spring:
  application:
    name: daebbang-api

  datasource:
    url: jdbc:mysql://localhost:3306/daebbang_local
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: false