ALTER TABLE users MODIFY COLUMN last_login_at DATETIME NULL;
ALTER TABLE users MODIFY COLUMN login_id VARCHAR(16) NOT NULL;
ALTER TABLE users MODIFY COLUMN name VARCHAR(50) NOT NULL;
ALTER TABLE users MODIFY COLUMN phone_number VARCHAR(20) NOT NULL;